spring.application.name=finance-tracker

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/finance_tracker}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:finance_tracker}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:finance_tracker}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
